### ISSUE TITLE
Handle multi-queries optimization

### ISSUE THREAD

**Issue by LLyaudet** [supabase/index_advisor#8]
Hello,

I just saw this repository listed on HN.
I like the idea.
At first, I thought it was completely trivial to optimize index creations for a single query.
And then I thought that it still would be nice to test all possibilities when you have a query with 15 distinct fields used in WHERE part.
Clearly, this is not hard to optimize when you know your data well,
but still it is better if you can automatize exhaustive search,
in case you missed some unknown feature of your data.
And you can also save some time.
So the base step is still interesting.
And the more interesting step(s) in my opinion is to handle queries distributions.
For example I worked on MySQL queries with a common part regarding tables and joins mainly, for a filter list view screen,
but maybe between 30 and 70 or 100 possible filters.
Somehow, in most cases, the trick was to simplify the job by forcing that a small datetime range filtered out most of the data.
But we had customers that were not using the parametring that forced small datetime ranges, or only on "normal users" and not on "admin" users.
And thus query building logic that I did generated optimized "USE INDEX" for MySQL.
(I don't remember if I also had to do some dynamic STRAIGHT JOIN for this/these query.)
But the fact is that I also had a policy of adding all indexes without looking too much on database size constraints.
In my current work, exploitation database size is way larger since we do not bound the timerange of history.
And thus the size of indexes matters much more.
If you could handle the optimization of choosing indexes in a clever way:

- for variations of the "same" query with objectives to minimize the size of indexes
- for queries using the same tables 
- for queries using sets of tables that are not disjoint
- for "connected components" of queries graph (an edge if sets of tables are not disjoint)

somehow with a continuum before and between these possibilities,
it would be nice.
Of course, think that the problem behind must be NP-complete.
But clearly, a good tool must help, because our approximate solutions by hand
are far from perfect most of the time unless the data has really distinct features and that you know them, or that you have a lot of luck.

Best regards,
     Laurent Lyaudet

**Comment by olirice** [comment]
We're on a similar page wrt the directions this can go.

The current implementation is quite minimal in that it only recommends single column btree indexes. Straightforward next steps  for improvement could be to consider other index types for relevant data types (e.g. GIN with jsonb_path_ops for jsonb columns) or multi-column indexes.

To your point, we currently exhaustively test potential indexes. As we expand to consider multi-column or multi-query indexes the combinatorial explosion makes that infeasible. We've discussed some heuristic methods but for now want to keep everything easy to understand and deterministic

I'm going to close this since its not immediately actionable, but if you have concrete ideas that are narrower in scope please feel free to open issues for them
